<?php
require __DIR__.'/app/bootstrap.php'; $u=require_user();
$iq=db()->prepare("SELECT i.*,o.order_number,s.name service_name FROM invoices i LEFT JOIN orders o ON o.id=i.order_id LEFT JOIN services s ON s.id=i.service_id WHERE i.user_id=? ORDER BY i.id DESC");$iq->execute([$u['id']]);$invoices=$iq->fetchAll();
$pq=db()->prepare("SELECT p.*,i.invoice_number FROM payments p JOIN invoices i ON i.id=p.invoice_id WHERE p.user_id=? ORDER BY p.id DESC LIMIT 50");$pq->execute([$u['id']]);$payments=$pq->fetchAll();
$sq=db()->prepare("SELECT s.*,p.name product_name FROM services s LEFT JOIN store_products p ON p.id=s.product_id WHERE s.user_id=? AND s.status<>'terminated' ORDER BY COALESCE(s.next_due_at,'9999-12-31'),s.id");$sq->execute([$u['id']]);$services=$sq->fetchAll();
$unpaid=array_filter($invoices,fn($i)=>in_array($i['status'],['unpaid','overdue'],true));$dueTotal=array_sum(array_map(fn($i)=>(float)$i['total'],$unpaid));$next=null;foreach($services as $s)if(!empty($s['next_due_at'])&&(!$next||strtotime($s['next_due_at'])<strtotime($next)))$next=$s['next_due_at'];
function client_side(string $active='billing', array $user):void{?><aside class="side"><div class="brand"><img src="/images/logo.png"><span>FOX<b>NETWORK</b></span></div><nav class="nav"><a href="/"><span>Overview</span></a><a href="/store.php"><span>Store</span></a><a href="/orders.php"><span>Orders</span></a><a class="<?=$active==='billing'?'active':''?>" href="/billing.php"><span>Billing</span></a><a href="/support.php"><span>Support</span></a></nav><nav class="nav bottom"><?php if(($user['role'] ?? '') === 'admin'): ?><a href="/admin/"><span>Admin</span></a><?php endif?><a href="/settings.php"><span>Account Settings</span></a><a href="/logout.php"><span>Sign out</span></a></nav></aside><?php }
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Billing | FoxNetwork</title><link rel="stylesheet" href="/assets/portal.css?v=<?=@filemtime(__DIR__.'/assets/portal.css')?>"></head><body><div class="app"><?php client_side('billing', $u);?><main class="main"><header><div class="profile"><div><b><?=e($u['name'])?></b><div class="muted small">Customer</div></div><div class="avatar"><?=e(strtoupper(substr($u['name'],0,1)))?></div></div></header><div class="content"><div class="eyebrow">CLIENT BILLING</div><h1>Billing & renewals.</h1><div class="muted">Invoices, payments, upcoming renewals and service cancellation in one place.</div>
<section class="stats"><div class="stat"><span class="muted">Outstanding</span><strong>€<?=number_format($dueTotal,2)?></strong></div><div class="stat"><span class="muted">Open invoices</span><strong><?=count($unpaid)?></strong></div><div class="stat"><span class="muted">Next renewal</span><strong style="font-size:18px"><?=e($next?date('d M Y',strtotime($next)):'—')?></strong></div></section>
<section class="card"><div class="cardhead"><b>YOUR SERVICES & RENEWALS</b><span class="muted"><?=count($services)?> services</span></div><?php if(!$services):?><div class="empty muted">No active services.</div><?php endif?><?php foreach($services as $s):$days=$s['next_due_at']?(int)floor((strtotime($s['next_due_at'])-time())/86400):null;?><div class="order-row"><div style="min-width:240px"><b><?=e($s['name'])?></b><div class="muted small"><?=e($s['product_name']??'Hosting service')?> · <?=e(ucfirst($s['status']))?></div></div><div><b>€<?=number_format((float)$s['price_monthly'],2)?></b><div class="muted small">/ <?=e($s['renewal_unit']??'month')?></div></div><div><b><?=e($s['next_due_at']?date('d M Y',strtotime($s['next_due_at'])):'Not set')?></b><div class="muted small"><?=e($days===null?'No automatic renewal':($days>=0?$days.' days remaining':abs($days).' days overdue'))?></div></div><span class="order-status status-<?=e($s['cancel_at_period_end']?'cancelled':$s['status'])?>"><?=e($s['cancel_at_period_end']?'CANCELS AT PERIOD END':strtoupper($s['status']))?></span><a class="btn" href="/lifecycle.php?service=<?=(int)$s['id']?>">Billing & cancellation</a></div><?php endforeach?></section>
<section class="card" style="margin-top:20px"><div class="cardhead"><b>INVOICES</b><span class="muted"><?=count($invoices)?> total</span></div><?php if(!$invoices):?><div class="empty muted">No invoices yet.</div><?php endif?><?php foreach($invoices as $r):?><div class="order-row"><div><b><?=e($r['invoice_number'])?></b><div class="muted small"><?=e($r['service_name']??$r['order_number']??'Account invoice')?> · Due <?=e(date('d M Y',strtotime($r['due_at'])))?></div></div><div class="order-price">€<?=number_format((float)$r['total'],2)?></div><span class="order-status status-<?=e($r['status'])?>"><?=e(strtoupper($r['status']))?></span><a class="btn" href="/invoice.php?id=<?=(int)$r['id']?>">View</a><?php if(in_array($r['status'],['unpaid','overdue'],true)):?><a class="btn primary" href="/pay.php?invoice=<?=(int)$r['id']?>">Pay with Mollie</a><?php endif?></div><?php endforeach?></section>
<section class="card" style="margin-top:20px"><div class="cardhead"><b>PAYMENT HISTORY</b><span class="muted"><?=count($payments)?> recent</span></div><?php if(!$payments):?><div class="empty muted">No payments recorded yet.</div><?php endif?><?php foreach($payments as $p):?><div class="order-row"><div><b><?=e($p['invoice_number'])?></b><div class="muted small"><?=e(ucfirst($p['provider']))?> · <?=e(date('d M Y H:i',strtotime($p['created_at'])))?></div></div><div class="order-price">€<?=number_format((float)$p['amount'],2)?></div><span class="order-status status-<?=e($p['status']==='completed'?'paid':$p['status'])?>"><?=e(strtoupper($p['status']))?></span></div><?php endforeach?></section>
</div></main></div></body></html>
