<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user();$id=(int)($_GET['id']??$_POST['id']??0);$serviceId=(int)($_GET['service']??$_POST['service']??0);$error='';
if($serviceId>0){$q=db()->prepare('SELECT id,config_json FROM services WHERE id=? AND user_id=? LIMIT 1');$q->execute([$serviceId,(int)$u['id']]);$item=$q->fetch();$root=json_decode((string)($item['config_json']??''),true)?:[];$cfg=(array)($root['domain']??[]);$domain=(string)($cfg['name']??'');}
else{$q=db()->prepare('SELECT oi.id,oi.config_json FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.id=? AND o.user_id=? LIMIT 1');$q->execute([$id,(int)$u['id']]);$item=$q->fetch();$cfg=json_decode((string)($item['config_json']??''),true)?:[];$domain=(string)($cfg['domain']??'');}
if(!$item||$domain===''||($cfg['dns_provider']??'oxxa')!=='oxxa'){http_response_code(404);die('OXXA domain not found.');}$domain=oxxa_domain_parts($domain)['domain'];
try{$groups=oxxa_nameserver_groups();}catch(Throwable $e){$groups=[];$error=$e->getMessage();}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$selected=trim((string)($_POST['nsgroup']??''));oxxa_domain_set_nsgroup($domain,$selected);$cfg['nsgroup']=$selected;if($serviceId>0){$root['domain']=$cfg;db()->prepare('UPDATE services SET config_json=? WHERE id=? AND user_id=?')->execute([json_encode($root,JSON_UNESCAPED_SLASHES),$serviceId,(int)$u['id']]);}else db()->prepare('UPDATE order_items SET config_json=? WHERE id=?')->execute([json_encode($cfg,JSON_UNESCAPED_SLASHES),$id]);$_SESSION['dns_flash']='Nameserver group changed. DNS availability can take some time.';header('Location: /domain-dns.php?'.($serviceId>0?'service='.$serviceId:'id='.$id));exit;}catch(Throwable $e){$error=$e->getMessage();}}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Choose NSGROUP</title><link rel="stylesheet" href="/assets/portal.css?v=<?=rawurlencode((string)@filemtime(__DIR__.'/assets/portal.css'))?>"></head><body class="portal-page"><?php render_client_page_start($u,'domains','Nameserver group');?><div class="eyebrow">OXXA NAMESERVERS</div><h1>Choose NSGROUP for <?=e($domain)?></h1><p class="muted">The domain is not currently connected to a group that supports this DNS zone. Select the group you want to use. Nothing changes until you confirm.</p><?php if($error):?><div class="error"><?=e($error)?></div><?php endif?><section class="card settings-card"><form method="post" class="admin-form-grid" style="padding:20px" onsubmit="return confirm('Change the authoritative nameserver group? Existing DNS and DNSSEC configuration may stop working.')"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="service" value="<?=$serviceId?>"><label class="fullfield">Nameserver group<select name="nsgroup" required><option value="">Choose an OXXA NSGROUP</option><?php foreach($groups as $group):?><option value="<?=e($group['handle'])?>" <?=($cfg['nsgroup']??'')===$group['handle']?'selected':''?>><?=e($group['name'])?> — <?=e($group['handle'])?></option><?php endforeach?></select></label><p class="muted fullfield">Changing nameservers removes old DNSSEC material to prevent invalid signatures. Copy any DNS records you still need before continuing.</p><div><button class="btn primary">Confirm NSGROUP</button> <a class="btn" href="/domains.php">Cancel</a></div></form></section><?php render_client_page_end();?></body></html>
