<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user();$error='';$domain=trim((string)($_POST['domain']??''));$dnsProvider=(string)($_POST['dns_provider']??'oxxa');
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        if(!oxxa_enabled())throw new RuntimeException('Domain ordering is currently disabled.');
        if(!in_array($dnsProvider,['oxxa','cloudflare'],true))throw new RuntimeException('Choose a valid DNS provider.');
        if(($dnsProvider==='oxxa'||oxxa_setting('test_mode','0')==='1')&&oxxa_setting('nsgroup')==='')throw new RuntimeException('OXXA Managed DNS is not configured by the administrator.');
        if($dnsProvider==='cloudflare'&&(cloudflare_setting('api_token')===''||cloudflare_setting('account_id')===''))throw new RuntimeException('Cloudflare DNS is not configured by the administrator.');
        foreach(['name','email','phone','street','house_number','postal_code','city','state','country_code'] as $field)if(trim((string)($u[$field]??''))==='')throw new RuntimeException('Complete your domain holder details in Account Settings first.');
        $domain=oxxa_domain_parts($domain)['domain'];if(!oxxa_domain_available($domain))throw new RuntimeException('This domain is not available for registration.');$quote=oxxa_domain_quote($domain,true);$price=(float)$quote['price'];$cost=(float)$quote['cost'];
        db()->beginTransaction();$number='FN-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$status=$price<=0?'paid':'pending';
        $q=db()->prepare("INSERT INTO orders(user_id,order_number,status,subtotal,total,currency) VALUES(?,?,?,?,?,'EUR')");$q->execute([(int)$u['id'],$number,$status,$price,$price]);$orderId=(int)db()->lastInsertId();
        $config=['service_type'=>'domain_registration','billing_period'=>'annual','domain'=>$domain,'dns_provider'=>$dnsProvider,'status'=>'pending','annual_price'=>$price,'oxxa_cost'=>$cost,'quoted_at'=>date('c')];
        db()->prepare("INSERT INTO order_items(order_id,product_id,product_name,unit_price,quantity,config_json) VALUES(?,NULL,?,?,1,?)")->execute([$orderId,'Domain registration: '.$domain,$price,json_encode($config,JSON_UNESCAPED_SLASHES)]);db()->commit();
        zoho_crm_try_sync_order($orderId);
        if($price>0){invoice_for_order($orderId);header('Location: /billing.php?created='.rawurlencode($number));exit;}
        provisioning_dispatch_order($orderId,['source'=>'free_domain_checkout']);header('Location: /domains.php?created='.rawurlencode($number));exit;
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
$q=db()->prepare('SELECT o.order_number,o.status order_status,o.created_at,oi.config_json,oi.unit_price FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.user_id=? AND oi.product_id IS NULL ORDER BY oi.id DESC');$q->execute([(int)$u['id']]);$domains=[];foreach($q->fetchAll() as $row){$cfg=json_decode((string)$row['config_json'],true)?:[];if(($cfg['service_type']??'')==='domain_registration'){$row['config']=$cfg;$domains[]=$row;}}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FoxNetwork | Domains</title><link rel="stylesheet" href="/css/fontawesome-all.min.css"><link rel="stylesheet" href="/assets/portal.css?v=<?=rawurlencode((string)@filemtime(__DIR__.'/assets/portal.css'))?>"></head>
<body class="portal-page"><?php render_client_page_start($u,'domains','Domain names');?><div class="eyebrow">DOMAIN STORE</div><h1>Find your domain.</h1><p class="muted">Live availability and pricing directly from OXXA.</p><?php if($error):?><div class="error"><?=e($error)?></div><?php endif?><?php if(isset($_GET['created'])):?><div class="notice">Domain order <?=e($_GET['created'])?> was created.</div><?php endif?>
<div class="checkout-grid"><section class="card form-card"><div class="cardhead"><b>REGISTER A DOMAIN</b></div><form method="post" class="order-form" id="domainOnlyForm"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><div class="field"><label>Domain name</label><input name="domain" required value="<?=e($domain)?>" placeholder="example.be" autocomplete="off"><div class="muted small" id="domainOnlyQuote">Enter a domain to check its price.</div></div><div class="field"><label>DNS provider</label><select name="dns_provider"><option value="oxxa" <?=$dnsProvider==='oxxa'?'selected':''?>>OXXA Managed DNS</option><option value="cloudflare" <?=$dnsProvider==='cloudflare'?'selected':''?>>Cloudflare DNS</option></select></div><button class="btn primary wide">Continue to payment</button></form></section>
<aside class="card summary"><div class="cardhead"><b>ORDER SUMMARY</b></div><div class="summary-body"><div class="summary-row"><span>Registration</span><b>1 year</b></div><div class="summary-row"><span>Registrar renewal</span><b>OXXA autorenew enabled</b></div><div class="summary-total"><span>Total due now</span><strong id="domainOnlyTotal">—</strong></div></div></aside></div>
<section class="card orders-card" style="margin-top:20px"><div class="cardhead"><b>YOUR DOMAINS</b><span class="muted"><?=count($domains)?> total</span></div><?php if(!$domains):?><div class="empty muted">No domain orders yet.</div><?php endif?><?php foreach($domains as $item):$cfg=$item['config'];?><div class="order-row"><div><b><?=e($cfg['domain']??'Domain')?></b><div class="muted small"><?=e(strtoupper((string)($cfg['dns_provider']??'oxxa')))?> DNS · <?=e(date('d M Y',strtotime($item['created_at'])))?></div></div><div class="order-price">€<?=number_format((float)$item['unit_price'],2)?></div><span class="order-status status-<?=e($item['order_status'])?>"><?=e(strtoupper((string)($cfg['status']??$item['order_status'])))?></span></div><?php endforeach?></section>
<script>const input=document.querySelector('[name="domain"]'),quote=document.getElementById('domainOnlyQuote'),total=document.getElementById('domainOnlyTotal');let timer=0,request=0;async function check(){const value=input.value.trim();if(!value){quote.textContent='Enter a domain to check its price.';total.textContent='—';return;}const current=++request;quote.textContent='Checking availability and price…';try{const response=await fetch('/api/domain-quote.php?domain='+encodeURIComponent(value),{headers:{Accept:'application/json'}}),data=await response.json();if(current!==request)return;if(!response.ok||!data.ok)throw Error(data.error||'Lookup failed.');if(!data.available){quote.textContent='This domain is already registered.';total.textContent='—';return;}const price=Number(data.quote.price);quote.textContent='Available · €'+price.toFixed(2)+' for the first year.';total.textContent='€'+price.toFixed(2);}catch(error){quote.textContent=error.message;total.textContent='—';}}input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(check,450)});if(input.value.trim())check();</script>
<?php render_client_page_end();?></body></html>
