<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user();$id=(int)($_GET['id']??$_POST['id']??0);$serviceId=(int)($_GET['service']??$_POST['service']??0);$error=(string)($_SESSION['dns_error']??'');$msg=(string)($_SESSION['dns_flash']??'');unset($_SESSION['dns_error'],$_SESSION['dns_flash']);
if($serviceId>0){$q=db()->prepare('SELECT id,config_json FROM services WHERE id=? AND user_id=? LIMIT 1');$q->execute([$serviceId,(int)$u['id']]);$item=$q->fetch();$root=json_decode((string)($item['config_json']??''),true)?:[];$cfg=(array)($root['domain']??[]);}
else{$q=db()->prepare('SELECT oi.id,oi.config_json FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.id=? AND o.user_id=? LIMIT 1');$q->execute([$id,(int)$u['id']]);$item=$q->fetch();$cfg=json_decode((string)($item['config_json']??''),true)?:[];}
if(!$item||empty($cfg)){http_response_code(404);die('Domain not found.');}$domainValue=$serviceId>0?($cfg['name']??''):($cfg['domain']??'');
if($domainValue===''||($serviceId<=0&&($cfg['service_type']??'')!=='domain_registration')){http_response_code(404);die('Domain not found.');}
$domain=oxxa_domain_parts((string)$domainValue)['domain'];$provider=(string)($cfg['dns_provider']??'oxxa');$zoneId=(string)($cfg['cloudflare_zone_id']??'');
if(!in_array((string)($cfg['status']??''),['active','test'],true)){http_response_code(403);die('DNS management is available after domain activation.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$records=domain_dns_records($domain,$provider,$zoneId);$action=(string)($_POST['action']??'');if($action==='add'){$record=domain_dns_validate($domain,(string)($_POST['name']??''),(string)($_POST['type']??''),(string)($_POST['content']??''),(int)($_POST['ttl']??3600),(int)($_POST['priority']??0));domain_dns_add($domain,$provider,$zoneId,$record);$msg='DNS record added.';}elseif($action==='delete'){$recordId=(string)($_POST['record_id']??'');$record=null;foreach($records as $candidate)if(hash_equals((string)$candidate['id'],$recordId)){$record=$candidate;break;}if(!$record)throw new RuntimeException('DNS record no longer exists.');domain_dns_delete($domain,$provider,$zoneId,$record);$msg='DNS record deleted.';}else throw new RuntimeException('Unknown DNS action.');}catch(Throwable $e){$error=$e->getMessage();}}
$records=[];try{$records=domain_dns_records($domain,$provider,$zoneId);}catch(Throwable $e){$error=$error?:$e->getMessage();$lower=strtolower($e->getMessage());if($provider==='oxxa'&&str_contains($lower,'nsgroup')&&(str_contains($lower,'niet op de juiste')||str_contains($lower,'not on the correct'))){header('Location: /domain-nsgroup.php?'.($serviceId>0?'service='.$serviceId:'id='.$id));exit;}}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($domain)?> DNS</title><link rel="stylesheet" href="/assets/portal.css?v=<?=rawurlencode((string)@filemtime(__DIR__.'/assets/portal.css'))?>"></head><body class="portal-page"><?php render_client_page_start($u,'domains','DNS management');?><div class="eyebrow"><?=e(strtoupper($provider))?> MANAGED DNS</div><h1><?=e($domain)?></h1><p class="muted">DNS changes can take time to propagate. Removing incorrect records can make websites or email unavailable.</p><?php if($msg):?><div class="notice"><?=e($msg)?></div><?php endif?><?php if($error):?><div class="error"><?=e($error)?></div><?php endif?>
<section class="card settings-card"><div class="cardhead"><b>ADD DNS RECORD</b><a class="link" href="/domains.php">Back to domains</a></div><form method="post" class="admin-form-grid" style="padding:20px"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="add"><label>Type<select name="type"><?php foreach(['A','AAAA','CNAME','MX','TXT'] as $type):?><option><?=$type?></option><?php endforeach?></select></label><label>Name / host<input name="name" placeholder="@ or www" required></label><label class="fullfield">Content<input name="content" placeholder="IP address, hostname or text" required maxlength="4096"></label><label>TTL<input type="number" name="ttl" min="60" max="86400" value="3600"></label><label>MX priority<input type="number" name="priority" min="0" max="65535" value="10"></label><div><button class="btn primary">Add record</button></div></form></section>
<section class="card" style="margin-top:20px"><div class="cardhead"><b>DNS RECORDS</b><span class="muted"><?=count($records)?> records</span></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Type</th><th>Name</th><th>Content</th><th>TTL</th><th>Priority</th><th></th></tr></thead><tbody><?php if(!$records):?><tr><td colspan="6" class="muted">No DNS records returned.</td></tr><?php endif?><?php foreach($records as $record):?><tr><td><b><?=e($record['type'])?></b></td><td><?=e($record['name'])?></td><td style="word-break:break-all"><?=e($record['content'])?></td><td><?=e($record['ttl'])?></td><td><?=e($record['priority'])?></td><td><form method="post" onsubmit="return confirm('Delete this DNS record?')"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="record_id" value="<?=e($record['id'])?>"><button class="btn danger">Delete</button></form></td></tr><?php endforeach?></tbody></table></div></section><?php render_client_page_end();?></body></html>
