<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user();
$serviceId=(int)($_GET['id']??0);
$q=db()->prepare('SELECT s.*,p.name product_name,p.linode_type,p.linode_region,p.linode_image FROM services s LEFT JOIN store_products p ON p.id=s.product_id WHERE s.id=? AND s.user_id=? LIMIT 1');
$q->execute([$serviceId,(int)$u['id']]);
$service=$q->fetch();
if(!$service||linode_service_provider($service)!=='linode'){http_response_code(404);die('VPS service not found.');}
header('Cache-Control: no-store, private');
$credentials=linode_service_credentials($service);
$instance=[];$apiError='';
if(!empty($service['linode_instance_id'])){try{$instance=linode_api('/linode/instances/'.(int)$service['linode_instance_id']);}catch(Throwable $e){$apiError=$e->getMessage();}}
$status=(string)($instance['status']??$service['status']??'pending');
$canPower=!empty($service['linode_instance_id'])&&in_array((string)$service['status'],['active','provisioning'],true);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($service['name'])?> | FoxNetwork VPS</title><link rel="stylesheet" href="/css/fontawesome-all.min.css"><link rel="stylesheet" href="/assets/portal.css?v=<?=rawurlencode((string)@filemtime(__DIR__.'/assets/portal.css'))?>"><style>
.vps-hero{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:20px}.vps-status{display:inline-flex;align-items:center;gap:8px;padding:8px 12px;border-radius:999px;background:rgba(34,197,94,.12);color:#5ee6a5;text-transform:uppercase;font-size:11px;font-weight:800}.vps-status i{width:8px;height:8px;border-radius:50%;background:currentColor}.vps-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.vps-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:18px}.vps-fact{padding:16px;border:1px solid var(--line,#283248);border-radius:12px}.vps-fact span{display:block;color:#8d98ad;font-size:11px;text-transform:uppercase;font-weight:800;margin-bottom:7px}.vps-fact b{word-break:break-all}.credential-row{display:grid;gap:7px;margin:14px 0}.credential-value{display:flex;gap:8px}.credential-value input{flex:1}.vps-actions{display:flex;gap:10px;flex-wrap:wrap;padding:18px}.vps-actions button{min-width:110px}@media(max-width:850px){.vps-grid{grid-template-columns:1fr}.vps-facts{grid-template-columns:1fr}.vps-hero{flex-direction:column}}
</style></head><body class="portal-page"><div class="app"><?php render_client_sidebar($u,'services');?><main class="main"><header><div class="profile"><div><b><?=e($u['name'])?></b><div class="muted" style="font-size:12px">Customer portal</div></div><div class="avatar"><?=e(strtoupper(substr((string)$u['name'],0,1)))?></div></div></header><div class="content">
<div class="vps-hero"><div><div class="eyebrow">Linode VPS</div><h1><?=e($service['name'])?></h1><p class="muted"><?=e($service['product_name']??'Virtual private server')?> · Instance #<?=e($service['linode_instance_id']??'pending')?></p></div><span class="vps-status" data-status><i></i><?=e($status)?></span></div>
<?php if($apiError):?><div class="error"><?=e($apiError)?></div><?php endif?>
<div class="vps-grid"><section class="card"><div class="cardhead"><b>VPS DETAILS</b></div><div class="vps-facts"><div class="vps-fact"><span>IPv4 address</span><b><?=e($credentials['ipv4']?:'Pending')?></b></div><div class="vps-fact"><span>IPv6 address</span><b><?=e($credentials['ipv6']?:'Pending')?></b></div><div class="vps-fact"><span>Plan</span><b><?=e($service['linode_type']??'—')?></b></div><div class="vps-fact"><span>Region</span><b><?=e($service['linode_region']??'—')?></b></div><div class="vps-fact"><span>Operating system</span><b><?=e($service['linode_image']??'—')?></b></div><div class="vps-fact"><span>Next due</span><b><?=e(empty($service['next_due_at'])?'Never':date('d M Y',strtotime((string)$service['next_due_at'])))?></b></div></div><div class="vps-actions"><button class="btn primary" data-power="start"><i class="fas fa-play"></i> Start</button><button class="btn" data-power="restart"><i class="fas fa-redo"></i> Restart</button><button class="btn danger" data-power="stop"><i class="fas fa-stop"></i> Stop</button></div></section>
<aside class="card"><div class="cardhead"><b>SSH ACCESS</b></div><div style="padding:18px"><div class="credential-row"><label>Username</label><div class="credential-value"><input id="ssh-user" value="root" readonly><button class="btn" type="button" data-copy="ssh-user">Copy</button></div></div><div class="credential-row"><label>Root password</label><div class="credential-value"><input id="ssh-password" type="password" value="<?=e($credentials['password'])?>" readonly><button class="btn" type="button" data-reveal="ssh-password">Show</button><button class="btn" type="button" data-copy="ssh-password">Copy</button></div></div><p class="muted small">Use SSH on port 22. Change the generated password after your first login. If you supplied a public key, key authentication is already configured.</p></div></aside></div>
</div></main></div><script>
const CSRF=<?=json_encode(csrf())?>,SERVICE_ID=<?=json_encode($serviceId)?>,CAN_POWER=<?=json_encode($canPower)?>;
if(!CAN_POWER)document.querySelectorAll('[data-power]').forEach(button=>{button.disabled=true;button.title='Power controls are unavailable for this service status.'});
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const input=document.getElementById(button.dataset.copy);await navigator.clipboard.writeText(input.value);button.textContent='Copied';setTimeout(()=>button.textContent='Copy',1200)}));
document.querySelectorAll('[data-reveal]').forEach(button=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.reveal);input.type=input.type==='password'?'text':'password';button.textContent=input.type==='password'?'Show':'Hide'}));
document.querySelectorAll('[data-power]').forEach(button=>button.addEventListener('click',async()=>{const buttons=[...document.querySelectorAll('[data-power]')];buttons.forEach(x=>x.disabled=true);try{const response=await fetch('/api/power.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':CSRF},body:JSON.stringify({id:String(SERVICE_ID),signal:button.dataset.power})});const result=await response.json();if(!result.ok)throw new Error(result.error||'Power action failed');document.querySelector('[data-status]').lastChild.textContent=' '+(button.dataset.power==='stop'?'shutting down':'starting');}catch(error){alert(error.message||String(error));}finally{setTimeout(()=>buttons.forEach(x=>x.disabled=!CAN_POWER),1200)}}));
</script></body></html>
