<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/blog.php';
$description='Practical guides, platform updates and hosting advice from FoxNetwork.';
$soroArticle=trim((string)($_GET['post']??''));
?>
<!doctype html><html lang="en-BE"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hosting Guides & News | FoxNetwork Blog</title>
<meta name="description" content="<?=e($description)?>"><?php if($soroArticle===''):?><link rel="canonical" href="<?=e(site_url('/blog/'))?>"><?php endif?><meta name="theme-color" content="#080b10">
<meta property="og:type" content="website"><meta property="og:title" content="FoxNetwork Blog"><meta property="og:description" content="<?=e($description)?>"><meta property="og:url" content="<?=e(site_url('/blog/'))?>">
<link rel="preconnect" href="https://app.trysoro.com" crossorigin><link rel="preconnect" href="https://afocirmbqdxnkyescnev.supabase.co" crossorigin>
<link rel="icon" href="/images/logo.png"><link rel="stylesheet" href="/css/fontawesome-all.min.css"><link rel="stylesheet" href="/assets/marketing.css?v=20260811c">
</head><body class="marketing-body">
<nav class="mk-nav" data-nav><div class="mk-wrap mk-nav-inner"><a class="mk-brand" href="/"><img src="/images/logo.png" alt="FoxNetwork"><span>FOX<b>NETWORK</b></span></a><button class="mk-mobile-toggle" type="button" data-nav-toggle aria-label="Open navigation"><i class="fas fa-bars"></i></button><div class="mk-links"><a href="/#hosting">Hosting</a><a href="/game-hosting/minecraft/">Game servers</a><a href="/vps-hosting/">Cloud VPS</a><a href="/discord-bot-hosting/">Free Discord hosting</a><a href="/blog/" aria-current="page">Blog</a><a href="/contact.html">Contact</a></div><div class="mk-actions"><a class="mk-button" href="/login.php">Sign in</a><a class="mk-button primary" href="/register.php">Create account</a></div></div></nav>
<main><header class="mk-blog-hero"><div class="mk-wrap"><span class="mk-kicker">FoxNetwork knowledge base</span><h1>Hosting, explained clearly.</h1><p>Practical guides, product updates and infrastructure advice for game servers, cloud VPS, websites and Discord bots.</p></div></header>
<section class="mk-section mk-soro-section"><div class="mk-wrap"><div class="mk-soro-shell"><div id="soro-blog"><div class="mk-soro-loading"><i class="fas fa-circle-notch fa-spin" aria-hidden="true"></i><span>Loading FoxNetwork articles…</span></div></div><noscript><div class="mk-blog-empty"><h2>JavaScript is required to view the blog.</h2><p>Enable JavaScript or contact FoxNetwork if you need help.</p><a class="mk-button primary" href="/contact.html">Contact FoxNetwork</a></div></noscript></div></div></section></main>
<footer class="mk-footer"><div class="mk-wrap"><div class="mk-footer-grid"><div><a class="mk-brand" href="/"><img src="/images/logo.png" alt=""><span>FOX<b>NETWORK</b></span></a><p>Independent Belgian hosting on European infrastructure, with automated deployment and direct support.</p></div><div><h3>Game hosting</h3><a href="/game-hosting/minecraft/">Minecraft</a><a href="/game-hosting/rust/">Rust</a><a href="/game-hosting/palworld/">Palworld</a><a href="/game-hosting/ark/">ARK</a></div><div><h3>Cloud & web</h3><a href="/vps-hosting/">Cloud VPS</a><a href="/discord-bot-hosting/">Discord bots</a><a href="/web-hosting/">Web hosting</a></div><div><h3>Company</h3><a href="/blog/">Blog</a><a href="/contact.html">Contact</a><a href="/privacy.html">Privacy</a><a href="/login.php">Client portal</a></div></div><div class="mk-footer-bottom"><span>© 2020–2026 FoxNetwork BV.</span><span>info@foxnetwork.be · +32 (0)2 615 76 80</span></div></div></footer>
<script src="https://app.trysoro.com/api/embed/7de016d4-6a20-4987-83c0-4564918ac116" defer></script><script>document.querySelector('[data-nav-toggle]')?.addEventListener('click',()=>document.querySelector('[data-nav]')?.classList.toggle('is-open'));</script></body></html>
