<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/blog.php';
$slug=blog_slugify((string)($_GET['slug']??''));
$stmt=db()->prepare("SELECT * FROM blog_posts WHERE slug=? AND status='published' AND published_at<=NOW() LIMIT 1");
$stmt->execute([$slug]);
$post=$stmt->fetch();
if(!$post){http_response_code(404);header('Content-Type: text/html; charset=utf-8');echo '<!doctype html><title>Article not found | FoxNetwork</title><style>body{background:#080b10;color:#fff;font:16px system-ui;display:grid;place-items:center;min-height:100vh}a{color:#ff7417}</style><main><h1>Article not found</h1><p><a href="/blog/">Back to the FoxNetwork blog</a></p></main>';exit;}
$title=trim((string)$post['meta_title'])?:$post['title'].' | FoxNetwork Blog';
$description=trim((string)$post['meta_description'])?:($post['excerpt']?:blog_excerpt_from_html((string)$post['content_html']));
$url=site_url('/blog/'.$post['slug'].'/');
$schema=['@context'=>'https://schema.org','@type'=>'BlogPosting','headline'=>$post['title'],'description'=>$description,'datePublished'=>blog_datetime_from_database((string)$post['published_at'],'c'),'dateModified'=>blog_datetime_from_database((string)$post['updated_at'],'c'),'mainEntityOfPage'=>$url,'author'=>['@type'=>'Organization','name'=>$post['author_name']?:'FoxNetwork Team'],'publisher'=>['@type'=>'Organization','name'=>'FoxNetwork BV','url'=>site_url('/')]];
if($post['hero_image'])$schema['image']=$post['hero_image'];
?>
<!doctype html><html lang="en-BE"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?></title><meta name="description" content="<?=e($description)?>"><link rel="canonical" href="<?=e($url)?>"><meta name="theme-color" content="#080b10"><meta property="og:type" content="article"><meta property="og:title" content="<?=e($title)?>"><meta property="og:description" content="<?=e($description)?>"><meta property="og:url" content="<?=e($url)?>"><?php if($post['hero_image']):?><meta property="og:image" content="<?=e($post['hero_image'])?>"><?php endif?><link rel="icon" href="/images/logo.png"><link rel="stylesheet" href="/css/fontawesome-all.min.css"><link rel="stylesheet" href="/assets/marketing.css?v=20260811b"><script type="application/ld+json"><?=json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script></head>
<body class="marketing-body"><nav class="mk-nav" data-nav><div class="mk-wrap mk-nav-inner"><a class="mk-brand" href="/"><img src="/images/logo.png" alt="FoxNetwork"><span>FOX<b>NETWORK</b></span></a><button class="mk-mobile-toggle" type="button" data-nav-toggle aria-label="Open navigation"><i class="fas fa-bars"></i></button><div class="mk-links"><a href="/#hosting">Hosting</a><a href="/game-hosting/minecraft/">Game servers</a><a href="/vps-hosting/">Cloud VPS</a><a href="/blog/" aria-current="page">Blog</a><a href="/contact.html">Contact</a></div><div class="mk-actions"><a class="mk-button" href="/login.php">Sign in</a><a class="mk-button primary" href="/register.php">Create account</a></div></div></nav>
<main><article class="mk-article"><header class="mk-article-head"><div class="mk-wrap mk-article-narrow"><a class="mk-blog-back" href="/blog/"><i class="fas fa-arrow-left"></i> All articles</a><div class="mk-blog-meta"><?php if($post['category']):?><span><?=e($post['category'])?></span><?php endif?><time datetime="<?=e(blog_datetime_from_database((string)$post['published_at'],'c'))?>"><?=e(blog_datetime_from_database((string)$post['published_at']))?></time></div><h1><?=e($post['title'])?></h1><?php if($post['excerpt']):?><p><?=e($post['excerpt'])?></p><?php endif?><small>By <?=e($post['author_name']?:'FoxNetwork Team')?></small></div></header><?php if($post['hero_image']):?><div class="mk-wrap mk-article-cover"><img src="<?=e($post['hero_image'])?>" alt=""></div><?php endif?><div class="mk-wrap mk-article-narrow mk-article-content"><?=$post['content_html']?></div></article><section class="mk-cta"><div class="mk-wrap"><div class="mk-cta-box"><div><h2>Need help choosing a service?</h2><p>Tell us what you want to run and we will help you find the right fit.</p></div><a class="mk-button primary" href="/contact.html">Ask FoxNetwork</a></div></div></section></main>
<footer class="mk-footer"><div class="mk-wrap"><div class="mk-footer-bottom"><span>© 2020–2026 FoxNetwork BV.</span><span><a href="/blog/">Blog</a> · <a href="/contact.html">Contact</a> · <a href="/privacy.html">Privacy</a></span></div></div></footer><script>document.querySelector('[data-nav-toggle]')?.addEventListener('click',()=>document.querySelector('[data-nav]')?.classList.toggle('is-open'));</script></body></html>
