<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/_layout.php';
$u=require_admin();$domains=[];$oxxaError='';$oxxaCount=0;$msg='';$error='';

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        if(($_POST['action']??'')!=='link_user')throw new RuntimeException('Unknown domain action.');
        $domain=oxxa_domain_parts((string)($_POST['domain']??''))['domain'];$userId=(int)($_POST['user_id']??0);
        $q=db()->prepare("SELECT id,name,email,role FROM users WHERE id=? LIMIT 1");$q->execute([$userId]);$customer=$q->fetch();if(!$customer)throw new RuntimeException('Choose a valid user.');
        $remote=null;foreach(oxxa_list_domains(true) as $item)if(strtolower(trim((string)($item['domainname']??'')))===$domain){$remote=$item;break;}
        if(!$remote)throw new RuntimeException('This domain was not found in the current OXXA account.');
        foreach(db()->query('SELECT config_json FROM order_items')->fetchAll() as $item){$cfg=json_decode((string)($item['config_json']??''),true)?:[];if(($cfg['service_type']??'')==='domain_registration'&&strtolower((string)($cfg['domain']??''))===$domain)throw new RuntimeException('This domain is already linked to a customer.');}
        foreach(db()->query('SELECT config_json FROM services')->fetchAll() as $item){$cfg=json_decode((string)($item['config_json']??''),true)?:[];if(strtolower((string)($cfg['domain']['name']??''))===$domain)throw new RuntimeException('This domain is already linked to a hosting service.');}
        db()->beginTransaction();$number='FN-LINK-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));
        $q=db()->prepare("INSERT INTO orders(user_id,order_number,status,subtotal,total,currency) VALUES(?,?,'active',0,0,'EUR')");$q->execute([$userId,$number]);$orderId=(int)db()->lastInsertId();
        $config=['service_type'=>'domain_registration','billing_period'=>'annual','domain'=>$domain,'dns_provider'=>'oxxa','status'=>'active','annual_price'=>0,'oxxa_cost'=>null,'registered'=>true,'imported_from_oxxa'=>true,'identity_handle'=>$remote['identity-registrant']??null,'nsgroup'=>$remote['nsgroup']??null,'expire_date'=>$remote['expire_date']??null,'autorenew'=>$remote['autorenew']??null,'lock'=>$remote['lock']??null,'registered_at'=>$remote['start_date']??date('c'),'linked_at'=>date('c')];
        db()->prepare("INSERT INTO order_items(order_id,product_id,product_name,unit_price,quantity,config_json) VALUES(?,NULL,?,0,1,?)")->execute([$orderId,'Imported domain: '.$domain,json_encode($config,JSON_UNESCAPED_SLASHES)]);db()->commit();
        audit_log('domain.link_user','domain',$domain,'Linked OXXA domain to user #'.$userId.'.');header('Location: /admin/domains.php?linked='.rawurlencode($domain));exit;
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
$customers=db()->query("SELECT id,name,email,role FROM users ORDER BY name,email")->fetchAll();

$standalone=db()->query("SELECT o.id order_id,o.order_number,o.status order_status,o.created_at,oi.id item_id,oi.unit_price,oi.config_json,u.id user_id,u.name customer_name,u.email FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN users u ON u.id=o.user_id WHERE oi.product_id IS NULL ORDER BY oi.id DESC")->fetchAll();
foreach($standalone as $row){$cfg=json_decode((string)$row['config_json'],true)?:[];if(($cfg['service_type']??'')!=='domain_registration'||empty($cfg['domain']))continue;$domains[]=['source'=>'domain-only','domain'=>$cfg['domain'],'customer_name'=>$row['customer_name'],'email'=>$row['email'],'user_id'=>$row['user_id'],'order_id'=>$row['order_id'],'order_number'=>$row['order_number'],'service_id'=>null,'status'=>$cfg['status']??$row['order_status'],'order_status'=>$row['order_status'],'dns_provider'=>$cfg['dns_provider']??'oxxa','price'=>$row['unit_price'],'cost'=>$cfg['oxxa_cost']??null,'identity'=>$cfg['identity_handle']??null,'oxxa_order_id'=>$cfg['oxxa_order_id']??null,'nsgroup'=>$cfg['nsgroup']??null,'cloudflare_zone_id'=>$cfg['cloudflare_zone_id']??null,'nameservers'=>$cfg['cloudflare_nameservers']??[],'registered_at'=>$cfg['registered_at']??null,'created_at'=>$row['created_at']];}

$hosting=db()->query("SELECT s.id service_id,s.order_id,s.status service_status,s.config_json,s.created_at,o.order_number,u.id user_id,u.name customer_name,u.email FROM services s JOIN users u ON u.id=s.user_id LEFT JOIN orders o ON o.id=s.order_id ORDER BY s.id DESC")->fetchAll();
foreach($hosting as $row){$cfg=json_decode((string)$row['config_json'],true)?:[];$domain=$cfg['domain']??null;if(!is_array($domain)||empty($domain['name']))continue;$domains[]=['source'=>'hosting','domain'=>$domain['name'],'customer_name'=>$row['customer_name'],'email'=>$row['email'],'user_id'=>$row['user_id'],'order_id'=>$row['order_id'],'order_number'=>$row['order_number'],'service_id'=>$row['service_id'],'status'=>$domain['status']??$row['service_status'],'order_status'=>$row['service_status'],'dns_provider'=>$domain['dns_provider']??'oxxa','price'=>$domain['annual_price']??null,'cost'=>$domain['oxxa_cost']??null,'identity'=>$domain['identity_handle']??null,'oxxa_order_id'=>$domain['oxxa_order_id']??null,'nsgroup'=>$domain['nsgroup']??null,'cloudflare_zone_id'=>$domain['cloudflare_zone_id']??null,'nameservers'=>$domain['cloudflare_nameservers']??[],'registered_at'=>$domain['linked_at']??null,'created_at'=>$row['created_at']];}
foreach($domains as &$domainRow){$domainRow['oxxa_live']=false;$domainRow['expire_date']=null;$domainRow['autorenew']=null;$domainRow['lock']=null;}unset($domainRow);
try{
    $remoteDomains=oxxa_list_domains(isset($_GET['refresh']));$oxxaCount=count($remoteDomains);$localIndex=[];foreach($domains as $index=>$domainRow)$localIndex[strtolower((string)$domainRow['domain'])]=$index;
    foreach($remoteDomains as $remote){$name=strtolower(trim((string)($remote['domainname']??'')));if($name==='')continue;
        if(isset($localIndex[$name])){$index=$localIndex[$name];$domains[$index]['oxxa_live']=true;$domains[$index]['expire_date']=$remote['expire_date']??null;$domains[$index]['autorenew']=$remote['autorenew']??null;$domains[$index]['lock']=$remote['lock']??null;$domains[$index]['nsgroup']=$remote['nsgroup']??$domains[$index]['nsgroup'];$domains[$index]['identity']=$remote['identity-registrant']??$domains[$index]['identity'];}
        else{$domains[]=['source'=>'oxxa-external','domain'=>$name,'customer_name'=>'OXXA account','email'=>'Not linked locally','user_id'=>null,'order_id'=>null,'order_number'=>null,'service_id'=>null,'status'=>'active','order_status'=>'active','dns_provider'=>'oxxa','price'=>null,'cost'=>null,'identity'=>$remote['identity-registrant']??null,'oxxa_order_id'=>null,'nsgroup'=>$remote['nsgroup']??null,'cloudflare_zone_id'=>null,'nameservers'=>[],'registered_at'=>$remote['start_date']??null,'created_at'=>$remote['start_date']??'','oxxa_live'=>true,'expire_date'=>$remote['expire_date']??null,'autorenew'=>$remote['autorenew']??null,'lock'=>$remote['lock']??null];}
    }
}catch(Throwable $e){$oxxaError=$e->getMessage();}
usort($domains,fn($a,$b)=>strcmp((string)($b['created_at']??''),(string)($a['created_at']??'')));
$unlinkedDomains=array_values(array_filter($domains,fn($d)=>$d['source']==='oxxa-external'));
$active=count(array_filter($domains,fn($d)=>in_array($d['status'],['active','test'],true)));$cloudflare=count(array_filter($domains,fn($d)=>$d['dns_provider']==='cloudflare'));
admin_head($u,'Domains','domains');
?>
<?php if(isset($_GET['linked'])):?><div class="notice"><?=e((string)$_GET['linked'])?> is now linked to the user.</div><?php endif?>
<?php if($error):?><div class="error"><?=e($error)?></div><?php endif?>
<?php if($oxxaError):?><div class="error">OXXA domain list unavailable: <?=e($oxxaError)?>. Local domain records are still shown.</div><?php endif?>
<div class="modern-admin-stats" style="margin-bottom:18px"><div class="admin-stat-card tone-blue"><span class="admin-stat-icon"><?=admin_icon('domains')?></span><div><small>REGISTERED DOMAINS</small><strong><?=count($domains)?></strong><span>All customer domain records</span></div></div><div class="admin-stat-card tone-green"><span class="admin-stat-icon"><?=admin_icon('domains')?></span><div><small>ACTIVE / TEST</small><strong><?=$active?></strong><span>Completed provisioning</span></div></div><div class="admin-stat-card tone-orange"><span class="admin-stat-icon"><?=admin_icon('domains')?></span><div><small>CLOUDFLARE DNS</small><strong><?=$cloudflare?></strong><span><?=count($domains)-$cloudflare?> use OXXA DNS</span></div></div></div>
<?php if($unlinkedDomains):?><section class="card settings-card" style="margin-bottom:18px"><div class="cardhead"><b>LINK OXXA DOMAIN TO USER</b><span class="muted"><?=count($unlinkedDomains)?> unlinked</span></div><form method="post" class="admin-form-grid" style="padding:20px"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="link_user"><label>OXXA domain<select name="domain" required><option value="">Choose domain</option><?php foreach($unlinkedDomains as $item):?><option value="<?=e($item['domain'])?>"><?=e($item['domain'])?></option><?php endforeach?></select></label><label>User<select name="user_id" required><option value="">Choose user</option><?php foreach($customers as $customer):?><option value="<?=e($customer['id'])?>"><?=e($customer['name'].' - '.$customer['email'].' ('.$customer['role'].')')?></option><?php endforeach?></select></label><div><button class="btn primary" type="submit" onclick="return confirm('Link this OXXA domain to the selected user?')">Link to user</button></div></form></section><?php endif?>
<section class="card"><div class="cardhead"><b>ALL REGISTERED DOMAINS</b><span class="muted"><?=$oxxaCount?> from OXXA · <?=count($domains)?> combined · <a class="link" href="?refresh=1">Refresh OXXA</a></span></div><div class="admin-search" style="padding:14px"><input id="domainSearch" placeholder="Search domain, customer, email or order…"></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Domain</th><th>Customer</th><th>DNS</th><th>Registration</th><th>Expiry</th><th>Price</th><th>Status</th></tr></thead><tbody id="domainRows"><?php if(!$domains):?><tr><td colspan="7" class="admin-empty-cell">No registered domains found.</td></tr><?php endif?><?php foreach($domains as $d):$search=strtolower(implode(' ',[$d['domain'],$d['customer_name'],$d['email'],$d['order_number'],$d['identity'],$d['oxxa_order_id']]));?><tr data-search="<?=e($search)?>"><td><b><?=e($d['domain'])?></b><small><?=e($d['source']==='hosting'?'Hosting add-on · Service #'.$d['service_id']:($d['source']==='oxxa-external'?'OXXA only · not linked locally':'Domain-only order'))?><?=!empty($d['registered_at'])?' · '.e(date('d M Y',strtotime($d['registered_at']))):''?></small></td><td><?=e($d['customer_name'])?><small><?=e($d['email'])?><?=$d['user_id']?' · User #'.e($d['user_id']):''?></small></td><td><b><?=e(strtoupper($d['dns_provider']))?></b><small><?=e($d['nsgroup']?:'No NS group yet')?></small><?php if($d['cloudflare_zone_id']):?><small>CF zone <?=e($d['cloudflare_zone_id'])?></small><?php endif?></td><td><b><?=e($d['order_number']?:'OXXA remote')?></b><small>Identity <?=e($d['identity']?:'pending')?><?=$d['oxxa_live']?' · Live':''?></small></td><td><?=e($d['expire_date']?:'—')?><small>Autorenew <?=e($d['autorenew']?:'—')?> · Lock <?=e($d['lock']?:'—')?></small></td><td><?=$d['price']!==null?'€'.number_format((float)$d['price'],2):'—'?><?php if($d['cost']!==null):?><small>Cost €<?=number_format((float)$d['cost'],2)?></small><?php endif?></td><td><?=admin_badge((string)$d['status'])?></td></tr><?php endforeach?></tbody></table></div></section>
<script>const search=document.getElementById('domainSearch');search?.addEventListener('input',()=>{const query=search.value.trim().toLowerCase();document.querySelectorAll('#domainRows tr[data-search]').forEach(row=>row.hidden=query!==''&&!row.dataset.search.includes(query));});</script>
<?php admin_foot(); ?>
