<?php require __DIR__.'/../app/bootstrap.php'; require __DIR__.'/_layout.php'; $u=require_admin();
$stats=[];$stats['customers']=(int)db()->query("SELECT COUNT(*) FROM users WHERE role='customer'")->fetchColumn();$stats['services']=(int)db()->query("SELECT COUNT(*) FROM services WHERE status='active'")->fetchColumn();$stats['tickets']=(int)db()->query("SELECT COUNT(*) FROM support_tickets WHERE status NOT IN ('closed','answered')")->fetchColumn();$stats['failed']=(int)db()->query("SELECT COUNT(*) FROM services WHERE status='failed'")->fetchColumn();$stats['unpaid']=(float)db()->query("SELECT COALESCE(SUM(total),0) FROM invoices WHERE status IN ('unpaid','overdue')")->fetchColumn();$stats['revenue']=(float)db()->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='completed'")->fetchColumn();
$orders=db()->query("SELECT o.*,u.name customer_name,u.email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.id DESC LIMIT 7")->fetchAll();$failed=db()->query("SELECT s.id,s.name,s.last_error,u.email FROM services s JOIN users u ON u.id=s.user_id WHERE s.status='failed' ORDER BY s.updated_at DESC LIMIT 5")->fetchAll();$ptero='OK';try{app_ptero('/nodes?per_page=1');}catch(Throwable $e){$ptero='ERROR';}
admin_head($u,'Dashboard','dashboard');?>
<div class="admin-stats"><div><span>Customers</span><strong><?=$stats['customers']?></strong></div><div><span>Active services</span><strong><?=$stats['services']?></strong></div><div><span>Open tickets</span><strong><?=$stats['tickets']?></strong></div><div><span>Failed provisioning</span><strong><?=$stats['failed']?></strong></div><div><span>Paid revenue</span><strong>€<?=number_format($stats['revenue'],2)?></strong></div><div><span>Outstanding</span><strong>€<?=number_format($stats['unpaid'],2)?></strong></div></div>
<div class="production-strip"><span>Pterodactyl API <b class="<?=$ptero==='OK'?'health-ok':'health-bad'?>"><?=e($ptero)?></b></span><span>Maintenance <b><?=app_setting('maintenance_mode','0')==='1'?'ON':'OFF'?></b></span><span>Mollie <b><?=cfg('mollie.api_key')?'CONFIGURED':'NOT SET'?></b></span></div>
<div class="admin-grid"><section class="card"><div class="cardhead"><b>RECENT ORDERS</b><a class="link" href="/admin/orders.php">View all</a></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><b><?=e($o['order_number'])?></b><small><?=e($o['created_at'])?></small></td><td><?=e($o['customer_name'])?><small><?=e($o['email'])?></small></td><td><?=admin_badge($o['status'])?></td><td>€<?=number_format((float)$o['total'],2)?></td></tr><?php endforeach?></tbody></table></div></section><section class="card admin-quick"><div class="cardhead"><b>PRODUCTION TOOLS</b></div><a href="/admin/migration.php">Paymenter migration <span>→</span></a><a href="/admin/security.php">Security & maintenance <span>→</span></a><a href="/admin/support.php">Support queue <span>→</span></a><a href="/admin/services.php">Service management <span>→</span></a></section></div>
<?php if($failed):?><section class="card" style="margin-top:20px"><div class="cardhead"><b>PROVISIONING NEEDS ATTENTION</b></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Service</th><th>Customer</th><th>Error</th></tr></thead><tbody><?php foreach($failed as $f):?><tr><td><a href="/admin/services.php"><b><?=e($f['name'])?></b></a></td><td><?=e($f['email'])?></td><td class="redtext"><?=e($f['last_error'])?></td></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<?php admin_foot(); ?>
